name: New API Request
description: Requirement for a new API to be built
title: "[API Request]: "
labels: ["backend", "triage"]
assignees:
  - karthikraman
body:
  - type: dropdown
    id: team
    attributes:
      label: Which team is requesting this new API?
      multiple: true
      options:
        - Business
        - Sales
        - FrontEnd
        - BackEnd
    validations:
      required: true   
  - type: textarea
    id: core-resource
    attributes:
      label: Core Resource
      description: The core resource to which this new API needs to be mapped.
      placeholder: /events
  - type: dropdown
    id: method
    attributes:
      label: Rest API Method
      options:
        - GET
        - POST
        - PUT
        - DELETE
    validations:
      required: true    
  - type: textarea
    id: endpoint
    attributes:
      label: Endpoint URL
      description: Endpoint of the API
      placeholder: /events
    validations:
      required: true
  - type: textarea
    id: api-description
    attributes:
      label: Description
      description: Description of the API and why it's required
      placeholder: /events
  - type: textarea
    id: sample-request
    attributes:
      label: API Request
      description: sample api request
      placeholder: curl
    validations:
      required: true
  - type: textarea
    id: sample-response
    attributes:
      label: API Response
      description: sample api response
      placeholder: {}
    validations:
      required: true    
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this new api request!
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true