name: New API Request
description: Requirement for a new API to be built
title: "[API Request]: "
labels: ["backend", "triage"]
assignees:
  - karthikraman
body:
  - type: dropdown
    id: team
    attributes:
      label: Which team is requesting this new API?
      multiple: true
      options:
        - Business
        - Sales
        - FrontEnd
        - BackEnd
    validations:
      required: true   
  - type: textarea
    id: core-resource
    attributes:
      label: Core Resource
      description: The core resource to which this new API needs to be mapped.
      value: "Ex: events. The value would be the first word in the API Path after the domain. API: "
  - type: dropdown
    id: method
    attributes:
      label: Rest API Method
      options:
        - GET
        - POST
        - PUT
        - DELETE
    validations:
      required: true    
  - type: textarea
    id: endpoint
    attributes:
      label: Endpoint URL
      description: Endpoint of the API
      value: "Sample Endpoint: /events"
    validations:
      required: true
  - type: textarea
    id: API Description
    attributes:
      label: description
      description: Description of the API and why it's required
      value: "Sample: "  
  - type: textarea
    id: samplerequest
    attributes:
      label: API Request
      description: sample api request
      value: "Sample API Request: curl "
    validations:
      required: true
  - type: textarea
    id: sampleresponse
    attributes:
      label: API Response
      description: sample api response
      value: "Sample API Response: {} "
    validations:
      required: true    
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
      options:
        - 1.0.2 (Default)
        - 1.0.3 (Edge)
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true